import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@mantine/core/styles.css";
import "./globals.css";
import MantineTheme from "@/mantine.config";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";

import SessionProvider from "./context/session";
import ReactQueryProvider from "./context/rquery";
import Layout from "@/app/components/layouts/primary";
import { Provider } from "jotai";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-mantine-color-scheme="light" lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={inter.className}>
        <MantineProvider theme={MantineTheme}>
          <main>
            <SessionProvider>
              <ReactQueryProvider>
                <Provider>
                  <Layout>{children}</Layout>
                </Provider>
              </ReactQueryProvider>
            </SessionProvider>
          </main>
          {/* <Footer /> */}
        </MantineProvider>
      </body>
    </html>
  );
}
