/* eslint-disable no-undef */
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import MantineTheme from "@/mantine.config";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { GoogleTagManager, } from "@next/third-parties/google";

import SessionProvider from "./context/session";
import ReactQueryProvider from "./context/rquery";
import Layout from "@/app/components/layouts/primary";
import { Provider } from "jotai";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Get Right Property",
  description: "Generated by Get Right Property",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html data-mantine-color-scheme="light" lang="en">
      <head>
        <ColorSchemeScript />
        {/* <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, maximum-scale=1, user-scalable=no"
        /> */}
   <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1,user-scalable=0,maximum-scale=1"/>
        <link
          rel="apple-touch-icon"
          sizes="57x57"
          href="/favicons/apple-icon-57x57.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="60x60"
          href="/favicons/apple-icon-60x60.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="72x72"
          href="/favicons/apple-icon-72x72.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="76x76"
          href="/favicons/apple-icon-76x76.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="114x114"
          href="/favicons/apple-icon-114x114.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="120x120"
          href="/favicons/apple-icon-120x120.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="152x152"
          href="/favicons/apple-icon-152x152.png"
        />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-icon-180x180.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/favicons/android-icon-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="96x96"
          href="/favicons/favicon-96x96.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicons/manifest.json" />
        <meta name="msapplication-TileColor" content="#ffffff" />
        <meta name="theme-color" content="#ffffff"/>
        {

        }
        {/* <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-17JGNNST9D"
        />
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: ` window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-17JGNNST9D');`,
          }}
        /> */}
      </head>
      <GoogleTagManager gtmId="G-TTFNJY2CX9"   />

      <body className={inter.className}>
        <MantineProvider theme={MantineTheme}>
          <main>
            <SessionProvider>
              <ReactQueryProvider>
                <Provider>
                  <Layout>{children}</Layout>
                </Provider>
              </ReactQueryProvider>
            </SessionProvider>
          </main>
          {/* <Footer /> */}
        </MantineProvider>
      </body>
    </html>
  );
}
