"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function LoginPage() {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const handleSubmit = async (event: any) => {
    event.preventDefault();

    // Perform login request
    const response = { ok: true, redirectUrl: "/my-profile" };

    if (response.ok) {
      // Redirect to the target URL based on the response
      const data = response;
      router.push(data.redirectUrl);
    } else {
      // Handle login failure
      alert("Login failed");
    }
  };
  return (
    <form onSubmit={handleSubmit}>
      <div>
        <label>
          Username:
          <input
            type="text"
            value={username}
            onChange={(e) => setUsername(e.target.value)}
          />
        </label>
      </div>
      <div>
        <label>
          Password:
          <input
            type="password"
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
        </label>
      </div>
      <button type="submit">Login</button>
    </form>
  );
}
let existingData = [
  {
    id: 13970,
    projid: 12,
    propType: 34,
    bhk: 42,
    bhkCustom: null,
    unitNumber: "Unit-001",
    tower: "100",
    phaseName: null,
    phaseId: 22,
    floor: 1,
    facing: 61,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1134",
    carpetArea: "908",
    gardenArea: "23",
    terraceArea: "44",
    balconyArea: "66",
    parkingArea: "55",
    plotArea: null,
    length: null,
    parkingType: null,
    width: null,
    bathroom: 1,
    balcony: 1,
    floorplan: 0,
    noOfCarParking: 1,
    isActive: "N",
    isDeleted: "N",
    isBasement: null,
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:12:31.000+05:30",
    modidate: "2024-06-21T12:12:31.000+05:30",
  },
  {
    id: 13973,
    projid: 12,
    propType: 32,
    bhk: null,
    bhkCustom: null,
    unitNumber: "s",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: null,
    facing: 62,
    facingCustom: null,
    block: null,
    superBuildUpArea: null,
    carpetArea: null,
    gardenArea: null,
    terraceArea: null,
    balconyArea: null,
    parkingArea: null,
    plotArea: "11",
    length: "11",
    parkingType: null,
    width: "11",
    bathroom: null,
    balcony: null,
    floorplan: 0,
    noOfCarParking: null,
    isActive: "N",
    isDeleted: "N",
    isBasement: null,
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:14:42.000+05:30",
    modidate: "2024-06-21T12:14:42.000+05:30",
  },
  {
    id: 14122,
    projid: 12,
    propType: 33,
    bhk: 40,
    bhkCustom: null,
    unitNumber: "unit 1",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 1,
    facing: 61,
    facingCustom: null,
    block: null,
    superBuildUpArea: "678",
    carpetArea: "550",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 1,
    balcony: 1,
    floorplan: 1,
    noOfCarParking: 1,
    isActive: "Y",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl:
      "https://getrightproperty-prod-bucket.s3.ap-south-1.amazonaws.com/images/varify/proj/12/33/14122/fp.jpg",
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T12:48:22.000+05:30",
  },
  {
    id: 14123,
    projid: 12,
    propType: 33,
    bhk: 41,
    bhkCustom: null,
    unitNumber: "unit 2",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 2,
    facing: 62,
    facingCustom: null,
    block: null,
    superBuildUpArea: "785",
    carpetArea: "654",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 2,
    balcony: 2,
    floorplan: 0,
    noOfCarParking: 2,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14124,
    projid: 12,
    propType: 33,
    bhk: 42,
    bhkCustom: null,
    unitNumber: "unit 3",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 3,
    facing: 63,
    facingCustom: null,
    block: null,
    superBuildUpArea: "980",
    carpetArea: "889",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 3,
    balcony: 3,
    floorplan: 0,
    noOfCarParking: 3,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14125,
    projid: 12,
    propType: 33,
    bhk: 43,
    bhkCustom: null,
    unitNumber: "unit 4",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 4,
    facing: 64,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1120",
    carpetArea: "991",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 4,
    balcony: 4,
    floorplan: 0,
    noOfCarParking: 4,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14126,
    projid: 12,
    propType: 33,
    bhk: 44,
    bhkCustom: null,
    unitNumber: "unit 5",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 5,
    facing: 65,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1356",
    carpetArea: "1140",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 5,
    balcony: 1,
    floorplan: 0,
    noOfCarParking: 3,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14127,
    projid: 12,
    propType: 33,
    bhk: 45,
    bhkCustom: null,
    unitNumber: "unit 6",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 6,
    facing: 66,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1440",
    carpetArea: "1356",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 4,
    balcony: 2,
    floorplan: 0,
    noOfCarParking: 1,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14128,
    projid: 12,
    propType: 33,
    bhk: 40,
    bhkCustom: null,
    unitNumber: "unit 7",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 7,
    facing: 67,
    facingCustom: null,
    block: null,
    superBuildUpArea: "678",
    carpetArea: "550",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 4,
    balcony: 3,
    floorplan: 0,
    noOfCarParking: 2,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14129,
    projid: 12,
    propType: 33,
    bhk: 41,
    bhkCustom: null,
    unitNumber: "unit 8",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 8,
    facing: 68,
    facingCustom: null,
    block: null,
    superBuildUpArea: "785",
    carpetArea: "654",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 1,
    balcony: 4,
    floorplan: 0,
    noOfCarParking: 3,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14130,
    projid: 12,
    propType: 33,
    bhk: 42,
    bhkCustom: null,
    unitNumber: "unit 9",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 9,
    facing: 61,
    facingCustom: null,
    block: null,
    superBuildUpArea: "980",
    carpetArea: "889",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 2,
    balcony: 5,
    floorplan: 0,
    noOfCarParking: 4,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14131,
    projid: 12,
    propType: 33,
    bhk: 43,
    bhkCustom: null,
    unitNumber: "unit 10",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 10,
    facing: 61,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1120",
    carpetArea: "991",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 3,
    balcony: 1,
    floorplan: 0,
    noOfCarParking: 5,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14132,
    projid: 12,
    propType: 33,
    bhk: 44,
    bhkCustom: null,
    unitNumber: "unit 11",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 1,
    facing: 62,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1356",
    carpetArea: "1140",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 4,
    balcony: 2,
    floorplan: 0,
    noOfCarParking: 6,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14133,
    projid: 12,
    propType: 33,
    bhk: 45,
    bhkCustom: null,
    unitNumber: "unit 12",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 2,
    facing: 63,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1440",
    carpetArea: "1356",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 5,
    balcony: 3,
    floorplan: 0,
    noOfCarParking: 7,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14134,
    projid: 12,
    propType: 33,
    bhk: 40,
    bhkCustom: null,
    unitNumber: "unit 13",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 3,
    facing: 64,
    facingCustom: null,
    block: null,
    superBuildUpArea: "678",
    carpetArea: "550",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 6,
    balcony: 4,
    floorplan: 0,
    noOfCarParking: 1,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14135,
    projid: 12,
    propType: 33,
    bhk: 41,
    bhkCustom: null,
    unitNumber: "unit 14",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 4,
    facing: 65,
    facingCustom: null,
    block: null,
    superBuildUpArea: "785",
    carpetArea: "654",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 1,
    balcony: 1,
    floorplan: 0,
    noOfCarParking: 2,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:28.000+05:30",
  },
  {
    id: 14136,
    projid: 12,
    propType: 33,
    bhk: 42,
    bhkCustom: null,
    unitNumber: "unit 15",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 5,
    facing: 66,
    facingCustom: null,
    block: null,
    superBuildUpArea: "980",
    carpetArea: "889",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 2,
    balcony: 2,
    floorplan: 0,
    noOfCarParking: 3,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14137,
    projid: 12,
    propType: 33,
    bhk: 43,
    bhkCustom: null,
    unitNumber: "unit 16",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 6,
    facing: 67,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1120",
    carpetArea: "991",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 3,
    balcony: 3,
    floorplan: 0,
    noOfCarParking: 4,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:30.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14138,
    projid: 12,
    propType: 33,
    bhk: 44,
    bhkCustom: null,
    unitNumber: "unit 17",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 7,
    facing: 68,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1356",
    carpetArea: "1140",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 4,
    balcony: 4,
    floorplan: 0,
    noOfCarParking: 5,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:31.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14139,
    projid: 12,
    propType: 33,
    bhk: 45,
    bhkCustom: null,
    unitNumber: "unit 18",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 8,
    facing: 69,
    facingCustom: null,
    block: null,
    superBuildUpArea: "1440",
    carpetArea: "1356",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 5,
    balcony: 1,
    floorplan: 0,
    noOfCarParking: 6,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:31.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14140,
    projid: 12,
    propType: 33,
    bhk: 40,
    bhkCustom: null,
    unitNumber: "unit 19",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 9,
    facing: 61,
    facingCustom: null,
    block: null,
    superBuildUpArea: "678",
    carpetArea: "550",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 1,
    balcony: 2,
    floorplan: 0,
    noOfCarParking: 1,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:31.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14141,
    projid: 12,
    propType: 33,
    bhk: 41,
    bhkCustom: null,
    unitNumber: "unit 20",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 10,
    facing: 62,
    facingCustom: null,
    block: null,
    superBuildUpArea: "785",
    carpetArea: "654",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 2,
    balcony: 3,
    floorplan: 0,
    noOfCarParking: 2,
    isActive: "N",
    isDeleted: "N",
    isBasement: "N",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:31.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14142,
    projid: 12,
    propType: 33,
    bhk: 42,
    bhkCustom: null,
    unitNumber: "unit 21",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 1,
    facing: 63,
    facingCustom: null,
    block: null,
    superBuildUpArea: "980",
    carpetArea: "889",
    gardenArea: "34",
    terraceArea: "55",
    balconyArea: null,
    parkingArea: "45",
    plotArea: "1200",
    length: null,
    parkingType: null,
    width: null,
    bathroom: 3,
    balcony: 4,
    floorplan: 0,
    noOfCarParking: 3,
    isActive: "N",
    isDeleted: "N",
    isBasement: "Y",
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl: null,
    createdate: "2024-06-21T12:47:31.000+05:30",
    modidate: "2024-06-21T07:17:29.000+05:30",
  },
  {
    id: 14145,
    projid: 12,
    propType: 33,
    bhk: 100013,
    bhkCustom: "23",
    unitNumber: "2",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 1,
    facing: 62,
    facingCustom: null,
    block: null,
    superBuildUpArea: "123",
    carpetArea: "1",
    gardenArea: "2",
    terraceArea: "2",
    balconyArea: null,
    parkingArea: "2",
    plotArea: "2",
    length: null,
    parkingType: "None",
    width: null,
    bathroom: 18,
    balcony: 4,
    floorplan: 1,
    noOfCarParking: 2,
    isActive: "N",
    isDeleted: "N",
    isBasement: null,
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl:
      "https://getrightproperty-prod-bucket.s3.ap-south-1.amazonaws.com/images/varify/proj/12/33/14145/fp.jpg",
    createdate: "2024-06-21T12:59:43.000+05:30",
    modidate: "2024-06-21T13:16:25.000+05:30",
  },
  {
    id: 14146,
    projid: 12,
    propType: 33,
    bhk: 100014,
    bhkCustom: "2.3",
    unitNumber: "22",
    tower: null,
    phaseName: null,
    phaseId: 22,
    floor: 1,
    facing: 65,
    facingCustom: null,
    block: null,
    superBuildUpArea: "22",
    carpetArea: "2",
    gardenArea: "2",
    terraceArea: "2",
    balconyArea: null,
    parkingArea: "2",
    plotArea: "2",
    length: null,
    parkingType: "None",
    width: null,
    bathroom: 18,
    balcony: 2,
    floorplan: 1,
    noOfCarParking: 2,
    isActive: "N",
    isDeleted: "N",
    isBasement: null,
    standardPlot: null,
    isChanged: null,
    editFloorPlan: null,
    isEdit: null,
    floorPlanUrl:
      "https://getrightproperty-prod-bucket.s3.ap-south-1.amazonaws.com/images/varify/proj/12/33/14146/fp.jpg",
    createdate: "2024-06-21T13:00:23.000+05:30",
    modidate: "2024-06-21T13:16:28.000+05:30",
  },
];
