name: Deploy Next.js App to AWS EC2

on:
  push:
    branches:
      - siva-next-test  # Trigger deployment on push to this branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub-hosted runner

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js environment
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build Next.js app
      - name: Build Next.js app
        run: npm run build 

      # Step 5: Save PEM key to a file
      - name: Create PEM file
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > key.pem
          chmod 600 key.pem  # Secure the key file

      # Step 6: Copy files to EC2
      - name: Copy necessary files to EC2 (excluding node_modules and .git)
        run: |
          scp -i key.pem -r --exclude 'node_modules/*' --exclude '.git/*' * \
          ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/opt/apps/code

      # Step 7: Trigger custom script on EC2
      - name: Trigger custom script on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            # Navigate to your app directory
            cd /opt/apps
            
            # Run your custom script
            bash ./prod.sh  # Replace with the path to your script
          EOF

      # Step 8: Cleanup
      - name: Remove PEM file
        run: |
          rm -f key.pem  # Remove the key file for security
